### ISSUE TITLE
When I first try to acess this project, I can't run basic.py .I used the backend of linux.

### ISSUE THREAD

**Issue by Leopold-Fitz-AI** [inspirai/wilderness-scavenger#15]
Running Episodes ... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "/home/leopold/marl/wilderness-scavenger/examples/basic.py", line 88, in <module>
    game.new_episode()
  File "/home/leopold/marl/wilderness-scavenger/inspirai_fps/gamecore.py", line 796, in new_episode
    self.__update_request()
  File "/home/leopold/marl/wilderness-scavenger/inspirai_fps/gamecore.py", line 783, in __update_request
    if self.__log_trajectory:
AttributeError: 'Game' object has no attribute '_Game__log_trajectory'

**Comment by chawuchen** [comment]
I had the same error, then I found gamecore.py updated yesterday.

**Comment by Leopold-Fitz-AI** [comment]
> I had the same error, then I found gamecore.py updated yesterday.

thanks
